### ISSUE TITLE
Chore Wheel!!!1

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#101]
We want to make a rotating list of things to check ahead of every meeting to encourage proper facilitation of the group.

We are imagining a chore wheel, like the animaniacs wheel of morality
![wheel of morality](https://user-images.githubusercontent.com/1355039/88705418-80793b80-d0dd-11ea-81c8-525fce6bf725.gif)

**Comment by ljharb** [comment]
![](https://img.buzzfeed.com/buzzfeed-static/static/2017-02/24/13/enhanced/buzzfeed-prod-web-06/anigif_enhanced-10588-1487959660-2.gif)

**Comment by dtex** [comment]
We were going to identify some tasks for the chore wheel correct?

- Note taker for Standards Team meetings
- Make sure an issue is created for the meeting
- Issue wrangler (triage new issues, close old issues, poke slow issues, tag issues where appropriate)
- Make sure meeting notes are captured in the repo
- Town crier (tell member projects about upcoming standards body meetings and their agendas)

Any other suggestions?

**Comment by MylesBorins** [comment]
The issue for the meeting is automated, so I think we can drop that from the wheel.

**Comment by jorydotcom** [comment]
this never quite took off... closing to find another solution!
