### ISSUE TITLE
Proposals for TC39

### ISSUE THREAD

**Issue by devsnek** [openjs-foundation/standards#102]
I'd like to bring two proposals to TC39:

- [`dbg!()`](https://docs.google.com/presentation/d/1TuLDmcjXuQmV3s6_thYCAlPaBLHO7ZM9pmCbS0oYcKw/edit#slide=id.p)
- [Elisions in FormalParameters](https://docs.google.com/presentation/d/1zMH6qMZ_lAIedVui8hH1__dXbATF3Ur8gZppAlGR_r4/edit#slide=id.p)

These proposals do not deal with any features specific to our projects but they would (in my opinion) improve JS as a whole, which we do have a vested interest in.

**Comment by ljharb** [comment]
I have zero idea what `dbg` is or does; could you elaborate?

**Comment by devsnek** [comment]
@ljharb sure. the idea is to have a standardized syntax or function or whatever that takes a value, performs some implementation defined printing/debugging of the value, and then returns the value. `console` is a thing of course but it doesn't exist across all implementations and you often have to refactor code to insert a console.log because it doesn't return its operand (and can't, since it's variadic)

**Comment by ljharb** [comment]
so like, it console.logs the `util.inspect` output and then returns the value?

**Comment by devsnek** [comment]
@ljharb that would be a reasonable expectation for how node would handle it, yes.

**Comment by ljharb** [comment]
Do these proposals have a repo?

**Comment by gibson042** [comment]
Regarding the first, I would expect a syntactic form based on `debugger`, following the pattern of either `eval` or meta properties like `new.target` (but it may be tricky to get any such concept past SES concerns).

Regarding the second, I'm for elision consistency, but think it will bleed into argument lists as well due to the cover grammars for normal and async concise functions.

**Comment by eemeli** [comment]
I like argument elision, esp. as that's how it already works with array destructuring:
```js
const [,,a] = [1, 2, 3]
a === 3
```

I don't think I quite see the point of `dbg!` as a core feature. It seems like it's just doing this?
```js
function dbg_(v) { console.log(v); return v; }
```
For some reason it's also now allowing `!` to show up in a place that currently causes a syntax error.

**Comment by devsnek** [comment]
@eemeli I'm not proposing we actually add it as `dbg!`, stage 1 is more about illustrating problems than providing solutions, and it often can be helpful to use features from existing languages (rust in this case) to reduce the amount of unfamiliar material.

@gibson042 in terms of specification sure, but we can make it a syntax error if we want (or allow it :shrug:). There is already the awkwardness of trailing comma after RestBindingElement so I don't think this is unprecedented.

@ljharb I'm planning to create repos if the standards group decides to move forward with these.

**Comment by jorydotcom** [comment]
Thank you @devsnek! 
I'm putting this issue on our agenda mostly to check with the group on how we're meant to proceed with proposals like this procedurally speaking - e.g. how tactically how we support community members with proposals. I would suggest we wait to open or transfer any proposal repo here until we've had the chance to sync up - sound good @openjs-foundation/standards ?

**Comment by jorydotcom** [comment]
Hi @devsnek - we wanted to check in and see if it is OK to remove this from our standards agenda for now, and see if there is any further commentary you need at the moment?

**Comment by ljharb** [comment]
Since both proposals were proposed (one achieved stage 1, one did not achieve stage 1), I assume there's nothing further.
