### ISSUE TITLE
Issue not created for today's meeting?

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/standards#103]
I have the meeting on my calendar, and it is on the OpenJS Foundation calendar. But no meeting issue was created

/cc @mhdawson re: the existing tool
/cc @mmarchini about ideas for a new tool based on github actions.

**Comment by mhdawson** [comment]
My machine has been a bit flaky and being on holiday last week I only caught that there was an issue on the weekend.  The Standards issue would have been opened on Friday so I'm sure that was it.

Happy to have other tools take over where it makes sense.

**Comment by devsnek** [comment]
i'd like to join whichever meeting #102 is discussed at.

**Comment by mmarchini** [comment]
If you don't need anything fancy (sync with Google Calendar and auto-generated Minutes), the Packages WG team wrote their own tooling: https://github.com/pkgjs/meet. Seems to be working for them and we're considering trying it out on the Diagnostics WG as well.

**Comment by MylesBorins** [comment]
@mmarchini we likely would like to generate some of these things. If we got a google api token into action env would that perhaps be able to help? We should potentially be able to even use the off the shelf tools that @mhdawson uses

**Comment by mmarchini** [comment]
Yes, with a Google API token you should be able to run the current scripts inside an Action (no need to use `meet` in that case).
