### ISSUE TITLE
Participation in the W3C Advisory Committee virtual meeting October 20

### ISSUE THREAD

**Issue by michaelchampion** [openjs-foundation/standards#109]
This is a request following the "Attending External Standards Meetings" governance guideline.

The OpenJS Foundation is a member of  the World Wide Web Consortium (W3C), having "inherited" the Node.js membership. Brian Kardell  @bkardell is the Foundation's representative to the W3C Advisory Committee (AC), but as I understand it he is participating on behalf of his "day job".  Since was involved in W3C for more than 20 years and represented Microsoft on the AC from 2007 - 2019 before my retirement early this year, he asked me to be his "alternate" so I can represent the Foundation's interests.

The AC is meeting via Zoom on October 20 to discuss pre-recorded presentations. These are available at https://www.w3.org/2020/10/TPAC/ac-agenda.html#materials for those of you who have W3C member access via the Foundation or your employer.

My intent in participating in this Q&A session is to monitor the discussion for any issues related to Javascript APIs, Frameworks, and challenges that users might bring up in the W3C context.  In my participation I will only represent the OpenJS Foundation, as I am not currently employed by anyone and my access to W3C member-confidential material is due to my volunteer work on the OpenJS Foundation Standards Working Group.  I will examine the meeting materials and discuss any topics this Foundation might want to speak to, and only address those that people such as @bkardell, @jorydotcom, and anyone else who expresses an interest believe are relevant to the Foundation.  In any event, I will prepare a meeting summary and be prepared to discuss any implications or followups with this Foundation's Standards WG.

Please advise.
Michael Champion

**Comment by MylesBorins** [comment]
This sounds good to me.

**Comment by bkardell** [comment]
+1 - and privately a few other people have also seemed to nod this is good - I'm not sure we actually have a process for approving this so if I don't hear some objection in the next day I am going to go ahead and do that and I can ask forgiveness later..
