### ISSUE TITLE
CPC Meeting time cadence change -- can standards cadence accommodate?

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/standards#115]
Hi friends. See the meeting link below relating to the update in the CPC meeting cadence.

Our plan is to go bi-weekly with our regular meetings but on the off-weeks have an optional working meeting at the same time as the regular meeting.

It would look like this:
week 1, 17:00 UTC: CPC Meeting
week 2, 17:00 UTC: CPC Working Meeting
week 3, 19:00 UTC: CPC Meeting
week 4, 19:00 UTC: CPC Working Meeting
and so on...

This will create a conflict with the Standards meeting. Can we (the Standards team) accommodate a schedule change as proposed? Thanks for considering!

Related issue:
https://github.com/openjs-foundation/cross-project-council/issues/680

**Comment by joesepi** [comment]
Perhaps we find a new time for the meeting so we dont have to worry about this at all? Perhaps we just move the meeting an hour earlier to be at 1800 UTC? Just a thought.

**Comment by MylesBorins** [comment]
We could consider moving the cadence of this meeting to monthly and ensure it doesn't conflict

- myles the meeting killer

**Comment by ljharb** [comment]
1800 utc monthly seems fine for now, but daylight savings will make it hard in spring :-/

**Comment by joesepi** [comment]
Hey friends. We just discussed this in today's CPC meeting.

Assuming Standards folks would be amenable, we decided to align and alternate Standards meetings with CPC meetings as such:
Week 1 - CPC 1900 | Standards 1700
Week 2 - Work 1900 | no Standards
Week 3 - CPC 1700 | Standards 1900
Week 4 - Work 1700 | no Standards

* "Work" means CPC working session

**Comment by joesepi** [comment]
Hey friends. I just chatted with Jory about this further and decided to just leave the dang Standards meeting alone. :) 

We may have conflicting CPC working sessions in the future, but let's cross that bridge when we get to it.

Thanks for enduring my meeting juggling adventure. Cheers!
