### ISSUE TITLE
Possible TAG nomination

### ISSUE THREAD

**Issue by bkardell** [openjs-foundation/standards#117]
I would like to propose that openjs nominate lea verou for w3c tag. She brings a great balance of views and experience that I think could be a benefit to TAG.  A few of us have discussed this and so far it seems positive, so putting it here.. The deadline to do so is Friday at midnight ET.

**Comment by michaelchampion** [comment]
See https://lea.verou.me/about/ for bio information on Lea, and https://lea.verou.me for her thoughts on technical matters.

**Comment by ljharb** [comment]
Presumably she’s on board with this? Should we tag `@leaverou` to confirm?

**Comment by bkardell** [comment]
@liharb "if she is, in the end, interested in running and accepting our nomination" is implied.  She is interested and would need someone to nominate her if she lands on a definite yes. There are plenty of options of who would be willing to, I think we should offer to nominate.

**Comment by MylesBorins** [comment]
+1. I've known Lea for a couple years and have always been impressed by their work.

**Comment by jorydotcom** [comment]
Ringing in another endorsement for Lea from me. 

Also sharing as this question was raised elsewhere, but we would be able to support them via our travel fund in the unlikely case that in-person travel is needed during the term.

**Comment by bkardell** [comment]
done.
