### ISSUE TITLE
TC39 Participation - Guy Bedford

### ISSUE THREAD

**Issue by guybedford** [openjs-foundation/standards#125]
I'd like to request TC39 participation through the OpenJS Foundation. Node.js as a runtime has very different requirements to browsers when it comes to the semantics of ES modules and as such could benefit from more representation, especially as it is both pushing the boundaries of and becoming a proving ground for a lot of the new modules standards.

As one of the authors of the top-level await specification which is being discussed at this next meeting on the 9th of March, I was informed that volunteering here as an OpenJS Foundation delegate might be a worthwhile route at this point.

I would be glad to represent the Node.js project in TC39 meetings going forward, with a focus on modules but also more generally as well.

**Comment by ljharb** [comment]
I support this.

**Comment by devsnek** [comment]
sgtm

**Comment by MylesBorins** [comment]
LGTM

**Comment by bnb** [comment]
+1

**Comment by joesepi** [comment]
+1. Thanks for volunteering!

**Comment by codebytere** [comment]
+1

**Comment by sendilkumarn** [comment]
+1 of course

**Comment by ljharb** [comment]
Given the next standards meeting is during this TC39 meeting, which/how many further approvals are needed to consider this approved? It'd be great to resolve this on Github before Tuesday.

**Comment by MylesBorins** [comment]
I say shipit

**Comment by guybedford** [comment]
This has been set up now, so will close the issue. Thank you all so much for the support! Also to mention, I'm also always available to discuss Node.js and TC39 topics anytime if anyone ever wants to get in touch via DM.
