### ISSUE TITLE
Deal with Recurring CPC Working Session Conflict

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#134]
Every other meeting for us there is a conflict with the CPC Working Session, which affects a few of our regular attendees. Let's figure out a rotation to avoid this moving forward.

**Comment by eemeli** [comment]
Have the meeting 2h earlier on conflicting days?

**Comment by ljharb** [comment]
Tuesdays 2 hours earlier partially conflicts with childcare duties, so I wouldn't be able to meet consistently during that timeslot if that's what we choose.

**Comment by joesepi** [comment]
I moved the Standards meeting up an hour to 1pm ET (instead of the usual 2pm ET). cc @jorydotcom.

This new schedule starts next meeting on May 4 -- May the fourth be with us.

**Comment by jorydotcom** [comment]
Thank you Joe!
