### ISSUE TITLE
Ad Hoc Meeting - Spec-Ed CG discussion with Marcos Caceres - April 28

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#137]
We'll be chatting with @marcoscaceres about the new Spec Editors Community Group that was just announced at the W3C, and learning more about how those projects might dovetail with ours. Note that there is an extreme timezone difference we're working with so we will be recording this session for those who can't make it. 

**Topic: Spec Ed CG + OpenJS Standards WG
Time: Apr 28, 2021 08:00 AM Eastern Time (US and Canada)**
See it in your local time: https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ad+Hoc+Standards+meeting+with+Spec+Ed+CG+Chair&iso=20210428T08&p1=%3A&ah=1

**Join Zoom Meeting
https://zoom.us/j/99094780293**

Meeting ID: 990 9478 0293
One tap mobile
+13017158592,,99094780293# US (Washington DC)
+13126266799,,99094780293# US (Chicago)

Dial by your location
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
        +1 646 558 8656 US (New York)
        +1 253 215 8782 US (Tacoma)
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        877 369 0926 US Toll-free
        855 880 1246 US Toll-free
        +1 647 374 4685 Canada
        +1 647 558 0588 Canada
        +1 778 907 2071 Canada
        +1 204 272 7920 Canada
        +1 438 809 7799 Canada
        +1 587 328 1099 Canada
        855 703 8985 Canada Toll-free
Meeting ID: 990 9478 0293
Find your local number: https://zoom.us/u/adgOA6mA5H

**Comment by jorydotcom** [comment]
Related, here is the repo and current open issues for the spec ed work if you want to watch/subscribe: https://github.com/w3c/speced-cg/issues

**Comment by jorydotcom** [comment]
For the interested - here's a link to the recording: 

> Topic: Spec Ed CG + OpenJS Standards WG
> Start Time : Apr 28, 2021 07:58 AM
> Meeting Recording:
> https://zoom.us/rec/share/1ZgST55z2HYITqdh45Kd-uP585CtElIIIp9oqbys2vhMnR0NVooBGGB5hyRgt9V1.frDTXaoY11Q0bJiF

We talked about: 

- How this group is 'bootstrapping' - what forms it is taking, how it is getting started etc
- How we are generalizing some educational materials to be non-SDO specific
- How to create a good 'Learning Path' for what it takes to become a spec editor
- Some of the challenges of getting involved, how W3C are looking at this as an opportunity to recruit new, diverse participants
- What are the skills needed, what are the benefits learning spec ed skills
- Designing learning materials

**Comment by bkardell** [comment]
interesting!

**Comment by marcoscaceres** [comment]
@bkardell, gives us a shout if you want to discuss anything or have any ideas or questions.
