### ISSUE TITLE
Define and Document the on-boarding process for the Representative

### ISSUE THREAD

**Issue by sendilkumarn** [openjs-foundation/standards#14]
The on-boarding document will make it clear to any one who will represent the Standards committee.

The document should list down but not limited to 
* Roles and responsibilities of the representative
* Things that they should take into consideration / know 
* Projects that are included and how to collaborate between them

Need to define an easy on-boarding process that will be clear for anyone who will be a representative.

**Comment by MylesBorins** [comment]
I feel like we've got the basics of this down. Please reopen (or ask me to) if I closed this prematurely
