### ISSUE TITLE
Document Delegates & Delegate Approval Process

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#142]
We were asked in Slack about who the OpenJS TC39 delegates are, and it turns out we don't keep that or other delegate info here.

**Comment by ljharb** [comment]
We should also summarize invited experts, and point folks to the right places for “how to get a proposal champion”

**Comment by eemeli** [comment]
Actually, it's more like we've not maintained the nominal list that we do have: https://github.com/openjs-foundation/standards/blob/main/MEMBER_REPRESENTATION.md

I'm actually a bit fuzzy on what my status wrt ECMA-402 is. Probably an invited expert? Or perhaps just "random person who keeps showing up".
