### ISSUE TITLE
Requesting 10 minutes to discuss API translation effort

### ISSUE THREAD

**Issue by mikesamuel** [openjs-foundation/standards#144]
Per [slack \#standards discussion](https://openjs-foundation.slack.com/archives/CKF0PCF54/p1623183396031400) maybe a few minutes to discuss an effort to make it easier for developer tools to display information about APIs in the user's preferred language.

Links for your clicking convenience:
- [Rough proposal draft](https://hackmd.io/@ErrorIsNullError/S1TWDOU5_)
- [Slides](https://docs.google.com/presentation/d/1g17IqaXD4IAYCkVS8odbK-G4ixSEK4KavxI1cXVwNo0/edit?usp=sharing)

**Comment by joesepi** [comment]
It would seem like this is a discussion @obensource should join, because of work on Node.js i18n and localization work

**Comment by obensource** [comment]
@joesepi @mikesamuel 100%! This is definitely something worth talking about with folks across the OpenJS ecosystem who'd be interested in the conversation (Steven Loomis, and Zeke Sikleanos come to mind).

I think next steps would be to set up an hour meeting a couple weeks out to talk more in depth about this topic, just to give enough time to solidify the time with folks form the OpenJSF, Unicode, node, tc39, etc. Does that sound good to you Mike?

Excited about this! 🎉

**Comment by mikesamuel** [comment]
@obensource That sounds great to me.
