### ISSUE TITLE
Stepping down as OSI Affiliate Representative

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/standards#170]
Hey All,

I just received an email notification to confirm that I am still the affiliate representative for the OpenJS foundation as there are upcoming elections running.

I unfortunately do not have the time to continue to do this work and as such am stepping down from my role. We should find someone else to pick this up.

**Comment by tobie** [comment]
I’m happy to take that role on.

**Comment by tobie** [comment]
Sorry for missing the call today. I often have conflicting commitments at that time (it's a coveted slot and conflicts with parental dinner responsibilities in the CET timezone). I would prefer that we operated in a more async manner if at all possible.

Our engagement with OSI should focus on the impeding EU and US legislation that aims to clarifying liability questions around software and might have an important impact on open source practitioners (especially in the EU) and open source usage.

I already liaise informally with the OSI's US and EU policy folks and OFE on these topics in a personal capacity and through my role as Senior Fellow for the Omidyar Network. This would essentially formalize work that I already do, allow me to provide insights to OpenJSF about these issues (as has been requested in the past), and possibly help liaise practitioners with policy makers who are clearly lacking and understanding of the situation and the impact some decisions could have on open source.
