### ISSUE TITLE
W3C LE Board

### ISSUE THREAD

**Issue by bkardell** [openjs-foundation/standards#185]
The W3C is in a kind of historic moment - it was founded with a particular model. It didn't really "exist" itself, but was rather a series of complex agreements among 'hosts' who actually did the operational things like provide facilities or pay staff and so on. This was centered in many ways on a few things - with MIT being very key, and a Director For Life at the center of almost everything.  A lot of that is changing - TimBL has been/is largely existing that, and MIT is going away as a host and  the W3C will become a legal entity itself, with its own financial responsibilities and ability to self-govern, etc.  

As part of that the legal entity requires a Board of Directors - the current plan is that this will be majority made up of people appointed _by membership itself_ through a nomination and election process.  The call for nominations opened yesterday and as members, we have the ability to nominate someone.  Nominations will remain open for a month.

**Comment by michaelchampion** [comment]
Jory would be a great candidate ;-) 

(A W3C AB member suggested this, don't blame me Jory !)

**Comment by bkardell** [comment]
I was also thinking this, tbh, but didn't want to suggest it :)
