### ISSUE TITLE
Concise Guide to Participating in Web Standards Document WIP

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#190]
Taking inpsiration from the OpenSSF's [recent concise guides](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/Concise-Guide-for-Evaluating-Open-Source-Software.md), we are collaborating on a "Concise Guide" of our own. 

Action: add suggested bullets for discussion / collaboration at next meeting [here](https://docs.google.com/document/d/1yDxUCnvZC23HfZXOz7OAbyWHZqqqNXBZHk0y3GBeIds/edit)

**Comment by michaelchampion** [comment]
I've been editing https://docs.google.com/document/d/1yDxUCnvZC23HfZXOz7OAbyWHZqqqNXBZHk0y3GBeIds/edit but don't see anyone else editing or commenting.  

Current title and questions are:
Concise Guide to Improving Web Standards
- What does it mean to be a “standard” ?  
- Which web standard is the source of truth and why? 
- How to read standards? 
- How do developers impact a standard?  
- What do published test suites actually test?
- Should I submit an API or format developed in an OSS project to a standards organization?

I'm not at all sure others agree with my draft answers to these questions, and I'm sure there are more questions JS developers have about web standards. Please take a look before the 09-20 meeting ;-)

**Comment by dtex** [comment]
Everything rings true, but one answer bothers me a little. 

> How to read standards? Don’t, unless you are implementing the standard or testing an implementation.

I agree that it is rarely the best starting point for someone looking to learn, but that's not really our audience here. I'd also argue that not all specs are equally obtuse, and some are quite approachable. Finally, the tone here could be considered condescending, and we want to encourage people to step outside their comfort zone. 

oh, and sometimes even in our roles as developers, we really do need to look at specs. I once found myself in a pickle that could only be understood by digging into 262. 

Maybe:

"The language found in specifications can sometimes be difficult to digest. The explanations and tutorials on sites such as MDN Web Docs https://developer.mozilla.org/en-US/ are generally more appropriate for developers looking to learn. 

Nevertheless, sometimes diving into a specification will be necessary. Many of those specs will have their own "How to Read" documents, such as [this for ECMA-262](https://timothygu.me/es-howto/). Also, [this post](https://alistapart.com/article/readspec/) is old but still very helpful for anyone new to standards."

Sorry to make it longer, but "Concise" is a skill that eludes me.

**Comment by michaelchampion** [comment]
Thanks, that's a great edit!  I've incorporated into the document.

**Comment by jorydotcom** [comment]
After latest revision, last call for notes/comments. Jory will incorporate these in time for the March 7 meeting, and we will collect +1s to ship at that time.
