### ISSUE TITLE
Possible TAG nomination — Reloaded 

### ISSUE THREAD

**Issue by LeaVerou** [openjs-foundation/standards#196]
_(Opening this per @rginn's suggestion in today's call)_

Howdy folks,

Two years ago, @bkardell suggested nominating me for the TAG by opening #117. @michaelchampion, @jorydotcom, @rginn, @ljharb, @MylesBorins endorsed it (thank you all), and [I was nominated by OpenJS](https://www.w3.org/2020/12/07-tag-nominations#lv), who also kindly offered to cover half of my travel expenses in the event I was elected (going splitsies with Bocoup). I was elected (🎉 ) despite that being one of the most competitive elections in the history of the TAG. There were two F2F meetings during my two year term, both in London (the rest were virtual).

After a lot of thought, I decided I'm willing to run again. Sure, it's a lot of unpaid work (~300 hours per year), but  I feel it's important work that needs doing. This assumes I can still have my travel covered (2-3 meetings a year + TPAC, though realistically some are going to be virtual, and I only need airfare for TPAC).

[Here's a draft of my statement for this election, which also talks about what I've been up to](https://docs.google.com/document/d/1q6Ns_szu97-_M1XXzvGje8MRZsDmH58Ly7dBsW11gE0/edit?usp=sharing) and [here's my 2020 statement](https://lea.verou.me/2020/11/tag/).
I'm still editing this year's statement (and trying to reduce its length!), so any feedback is welcome. 😊

Please note that the deadline for nominations is **November 8th**, so time is of the essence.

Cheers!

**Comment by michaelchampion** [comment]
Looks good!  Maybe ....
- Start with a strong opening sentence stressing that your independence,  UX research, CSS, and TAG  experience can help the TAG stay connected to the user and developer community, and better serve their needs by ensuring web platform features are usable, secure and privacy preserving.
- Maybe do some polishing to highlight your role in driving the TAG design principles and speeding up the spec review process so it generates feedback at the design stage
- Maybe end with an explicit commitment to spend the hundreds of hours a year needed to be an effective TAG member. (The sense that some candidates were "too busy" and didn't explicitly commit to invest the needed time apparently cost them votes in the recent Board election)
-

**Comment by LeaVerou** [comment]
> Maybe end with an explicit commitment to spend the hundreds of hours a year needed to be an effective TAG member.

Done

> Possibly link to your Wikipedia entry

Done, as a subtle link on "Lea".

> Looks good! Maybe ....

Thanks for the feedback! I'll work on the other points, but stepping back for a moment, the main things are 
a) Does OpenJS want to nominate me again? 
b) Can OpenJS fund my travel?

**Comment by ljharb** [comment]
I’d vote yes on both things.

**Comment by tobie** [comment]
> I’d vote yes on both things.

+1

**Comment by jorydotcom** [comment]
We submitted Lea's nomination today! Closing this issue out. :heart:
