### ISSUE TITLE
Possible W3C Advisory Board Nomination

### ISSUE THREAD

**Issue by michaelchampion** [openjs-foundation/standards#197]
The W3C Advisory Board will have an election to 4 seats opening because AB members elected to the Board of Directors have all decided they are too busy to do both. OpenJS Foundation should consider whether we want to nominate a candidate.  We have until 30 November to decide.

 https://lists.w3.org/Archives/Member/w3c-ac-members/2022OctDec/0015.html has the details.

> As announced by Léonie Watson in 1 November email to the AC [1], David 
Singer, Eric Siow, Léonie Watson, and Hongru (Judy) Zhu are resigning 
from the Advisory Board effective 2 January 2023.

> Per section 3.3.3.5 of the Process [2], when those seats become vacant 
they will be up for election at the next regularly scheduled AB election 
(to start in April 2023). The AB chairs have requested an earlier 
election to begin in December to fill the remaining terms of those 
seats. They have further requested that we call for nominations 
immediately without an advance notice period.

> This is a Call for Nominations for an election to begin on 2 December 
and end on 14 January to fill those vacancies. Three of the terms 

Unlike previous AB elections, the nominations are public as soon as they are made, see https://www.w3.org/2022/11/ab-nominations . I suggest we track this URL and periodically assess whether the existing candidates list has a good set of qualified people, and consider nominating someone if not.  Likewise, we should be open to others not affiliated with a W3C member but asks for us to nominate them.

**Comment by ljharb** [comment]
What are the requirements for candidates?

**Comment by michaelchampion** [comment]
You don’t have to work for a W3C member, there have been several “invited experts” serving on the AB.

Not sure if there are formal requirements beyond not working for the same company as another AB member, agreeing to follow the Code of Ethics and Professional Conduct, etc..  

https://www.w3.org/wiki/AB/Being_on_the_AB is an informal “job description”, but was written before the responsibility to serve on Formal Objection Councils was added.
