### ISSUE TITLE
Becoming a TC39 delegate

### ISSUE THREAD

**Issue by LeaVerou** [openjs-foundation/standards#211]
Hello,

After some recent discussions, @ljharb suggested it would help if I became a TC39 delegate so I could have better access to TC39 internal channels. This came up recently as we wanted to solicit TC39 input in a couple TAG discussions, but I did not have access in certain private repos that would be best for that. Beyond that, I do have personal interest in participating in TC39 discussions and have filed a couple proposals around ESM recently, so I'd love to be able to participate properly as an OpenJS delegate. 

_(I became a Standards WG participant in https://github.com/openjs-foundation/standards/pull/199 )_

**Comment by ljharb** [comment]
I won't be in the standards meeting next week, but I obv vote yes on this. If it's approved, and @gibson042 files the onboarding issue, I can onboard Lea very quickly.

**Comment by gibson042** [comment]
Sure thing. @LeaVerou, can you provide the requested information?

- Pronouns
- Email address (_you can DM me via `@gibson042:matrix.org` or Twitter to avoid sharing here if you like_)
- Matrix username (_optional but recommended_)
- https://es.discourse.group/ username (_optional_)
- Three-letter [`notes`](https://github.com/tc39/notes/edit/main/delegates.txt) initials (_presumably "LVU" per [tc39/how-we-work](https://github.com/tc39/how-we-work/blob/main/how-to-take-notes.md#the-attendee-list)—first letter of first name, first letter of last name, last letter of last name_)

**Comment by LeaVerou** [comment]
@gibson042 Sure, thanks!

* Pronouns: she/her
* Email address: lea ⓐⓣ verou.me
* Matrix username: @leaverou:matrix.org
* es.discourse.group username: [LeaVerou](https://es.discourse.group/u/LeaVerou)
* Three-letter [`notes`](https://github.com/tc39/notes/edit/main/delegates.txt) initials: I'm fine with LVU

**Comment by gibson042** [comment]
Thanks. I also vote yes, and opened an issue for TC39 marked pending until the OpenJSF meeting.

**Comment by jorydotcom** [comment]
+1!

**Comment by eemeli** [comment]
+1

**Comment by joesepi** [comment]
+1

**Comment by michaelchampion** [comment]
+1

**Comment by jorydotcom** [comment]
Sweet, we're good! @ljharb @LeaVerou @gibson042

**Comment by LeaVerou** [comment]
Thanks everyone! 🙏🏼

Should I be added here? https://github.com/openjs-foundation/standards/blob/main/MEMBER_REPRESENTATION.md
Someone brought this link up in https://github.com/tc39/Admin-and-Business/issues/312
