### ISSUE TITLE
Clean up Working Group Members List

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#215]
We need to update the Standards WG [Member Roster](https://github.com/openjs-foundation/standards#working-group-members) to reflect active members as this helps us determine our quorum for decision-making. PR incoming to update / distinguish active (has attended meetings and/or participated in online discussions within the past year) vs. inactive members (have not participated in the past year).

**Comment by michaelchampion** [comment]
I thought I was "active" but maybe not?

**Comment by jorydotcom** [comment]
@michaelchampion you are definitely active!!
