### ISSUE TITLE
Nominations open for W3C Advisory Board

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#223]
@bkardell reminded us that the call for nominations is open for 6 AB positions, through May 26. If there is anyone you think we should encourage to nominate, please bring that forward to the group.

**Comment by tobie** [comment]
I've considered [running again](https://www.w3.org/2022/11/ab-nominations#tl). If so, would OpenJSF be willing to nominate me?

**Comment by jorydotcom** [comment]
I apparently mis-read the timeline and the nomination period has closed already, so this issue will be closed.
