### ISSUE TITLE
Request to be designated as W3C AC alternate for next W3C AC F2F 

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/standards#226]
As brought up in our [April 4 meeting](https://github.com/openjs-foundation/standards/blob/main/meeting-notes/2023.04.04_meeting_notes.md#openjs-foundationstandards), I'd like to represent the OpenJSF at W3C's upcoming Advisory Committee meeting in Nice (which is close to home, so small travel costs). I have been asked by one of the W3C's Advisory Board chairs to run a breakout session on "working together" sparked in particular by my proposal to create an Advisory Committee Chair position (see [mailing list thread](https://lists.w3.org/Archives/Member/w3c-ac-forum/2021OctDec/0284.html) and [GitHub Issue](https://github.com/w3c/AB-memberonly/issues/163)), now that the bylaws clarify the membership's role.

This is the first AC meeting following W3C successfully transitioning into an independent legal entity. It's a good point in time to be involved with the organization and help shape the role of the membership in the organization.

To join the AC meeting on behalf of the OpenJSF, I need to be designated as [alternate](https://www.w3.org/2021/Process-20211102/#alternate-ac-representative) by OpenJSF's AC Representative (currently @jorydotcom) as per [W3C Process § 3.2.2](https://www.w3.org/2021/Process-20211102/#ac-participation).

My understanding from our conversation on April 4 was that we were going to manage this offline, but I haven’t received a reply to my various emails on the topic and the AC meeting is early May. I'd like to be able to confirm that I'll be facilitating this session as soon as possible.

**Comment by jorydotcom** [comment]
@tobie as we're working through the hoop-jumping to get your account affiliated - what's the travel cost estimate?

**Comment by jorydotcom** [comment]
Summarizing from the meeting today; the WG approved this and the travel expense. @tobie you should be designated appropriately now on the W3C Member Portal.
