### ISSUE TITLE
TC-53 Participation

### ISSUE THREAD

**Issue by dtex** [openjs-foundation/standards#24]
Last year ECMA launched TC-53, a group focused on ECMAScript modules for embedded systems. I was invited to attend the first in-person meeting and have been participating in all the meetings since. Other familiar faces that have been attending are @jorydotcom and @rwaldron.

Since the focus is embedded systems I feel it's important that we have a representation for the rest of JavaScript (node & browsers) so that we are not forgotten in any standards set by the committee. The embedded systems folks, who are awesome and brilliant, don't necessarily worry about some of the things that we frequently do. Asynchronous behavior is a good example of one of those things.

They've done a great job of addressing these types of concerns when they are raised but someone needs to be there to raise them. I'm confident that as long as there are literally enough seats at the table I'll be welcome, but one day they'll need that seat for a paying member.

That's why I'm opening this issue. The OpenJS Foundation is an ECMA member and is guaranteed seats at the TC-53 table. I'd like to volunteer to be an OpenJS representative on TC-53. It will give me comfort to know that my ability to contribute is not at risk. @rwaldron is the obvious choice for this role given the breadth and depth of his expertise, but both he and Jory are already participating in TC-53 on behalf of Bocoup.

Is anybody else interested in this role? 

I don't believe this would have any monetary impact on OpenJS foundation. The membership in ECMA extends to all TC's.

**Comment by dtex** [comment]
So there don't seem to be any objections. What would be the next steps?

**Comment by MylesBorins** [comment]
I've added the agenda label so we can discuss in the next meeting, which you should feel free to join.

We are currently documenting a process to identify foundation reps... perhaps you could help with that?

Please correct me if I'm wrong but the explicit ask is for:

* OpenJS to participate in TC-53
* For you to be the rep.

**Comment by dtex** [comment]
> • OpenJS to participate in TC-53
> • For you to be the rep.

Yes, exactly.

**Comment by jorydotcom** [comment]
Just commenting with the discussion summary from our meeting yesterday: we're going to see about registering the OpenJS Foundation as a member to the TC53 committee, and talk to our Foundation Legal about what agreements we need to make sure our secured between the foundation and our delegates. One possible approach is utilizing an invited expert form, which we will also work with Little Dan about for TC39.

**Comment by dtex** [comment]
Happy New Year Standards Team. I wanted to check in and make sure there was no leg work I needed to be doing on my end to help with this.

**Comment by dtex** [comment]
Per a recent Standards Team meeting, I believe that this is (paraphrasing) just waiting on legal from the OpenJS side.

If we don't expect that soon, I propose that we just close this issue. My seat at the table is not in danger and I had not planned on requesting travel funds.

@jorydotcom should we just close this?
