### ISSUE TITLE
Be a founding member of Open Policy Alliance (an OSI project)

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/standards#243]
The Open Source Initiative (OSI) is launching a new project called Open Policy Alliance.

The goal of this project is to be a one-stop-shop for policy makers to:

1. Learn about open source.
2. Know who to talk to when policy or legislation risks impacting open source.

This is an important and much needed effort that we really should support. It's very well aligned with [the reasons we had for reinvesting into OSI](https://github.com/openjs-foundation/standards/issues/170#issuecomment-1532164010) and with the forward thinking approach we've been having to the broader ecosystem lately (Alpha Omega funding for jQuery, Sovereign Tech Fund, etc.)

I'd love for OpenJSF to be part of the founding members, but the timing is fairly short: we have to inform OSI by tomorrow morning (June 19th). I got the email Friday, forwarded it right away to @jorydotcom, @rginn, and @kyliewd, but didn't get a chance to open an issue here until today.

If there's a massive and quick outpour of +1 to this _and_ approval from @rginn, I'll go ahead and let the OSI know were willing to be part of this from the get go.

**Comment by ljharb** [comment]
I’m in support of this - but it’s unfortunate they chose a deadline that’s a US federal holiday.

**Comment by tobie** [comment]
Good point. Weird given the lead for the project is Deb who is based in the US. I've pinged her to ask.

**Comment by michaelchampion** [comment]
What are the obligations of "founding members?"  Is money involved?

**Comment by tobie** [comment]
> What are the obligations of "founding members?" Is money involved?

None. It’s just a motion of confidence and support.

**Comment by jorydotcom** [comment]
Discussed in today's WG meeting; we agreed that we would support this and would like to ask the OpenJS Foundation Board to review and ideally approve (@rginn @bensternthal)

**Comment by tobie** [comment]
So for the record, providing support for this project doesn't require any additional agreement or MoU with OSI.

**Comment by ctcpip** [comment]
+1 

this seems like a no-brainer; we should be at the table

**Comment by joesepi** [comment]
+1 from me as well.

**Comment by tobie** [comment]
WG approved moving forward with this during its bi-weekly call on July 25.
