### ISSUE TITLE
TPAC Open Office Hours

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#25]
Posting this to offer time for any OpenJSF project to connect with those of us going to TPAC this year (cc @MylesBorins @christian-bromann @bkardell)

Tentatively planning for Wednesday, Sept. 11 @ 12 p.m. EST; let me know with a 👍 or 👎 if you're able to attend!

**Comment by MylesBorins** [comment]
I'm en route to Japan next Tuesday so may need slightly more flexible times during the day

**Comment by bkardell** [comment]
I can attend, however this conflicts with csswg, so it means choosing between the two.

**Comment by jorydotcom** [comment]
Hi All, I didn't do a good job getting this organized, but JIK folks can make it today I'm going to keep the time. Unfortunately I fly out for Japan on Friday so there's not much time left to make this happen!

You are invited to a Zoom webinar. 
When: Sep 11, 2019 12:00 PM Eastern Time (US and Canada)
Topic: TPAC Office Hours 

Please click the link below to join the webinar: 
https://zoom.us/j/368758518

Or iPhone one-tap :
    US: +16465588656,,368758518#  or +16699006833,,368758518# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8656  or +1 669 900 6833  or 855 880 1246 (Toll Free) or 877 369 0926 (Toll Free)
        Canada: +1 647 558 0588  or 855 703 8985 (Toll Free)
    Webinar ID: 368 758 518
    International numbers available: https://zoom.us/u/akVmLCTid

**Comment by jorydotcom** [comment]
Recapping for posterity: we discussed an outline for our breakout session if we are able to have that (due to space limitations). We also discussed making formal invitations to the TC39 outreach groups and coming up with selection of tech issues we might want the Standards WG to consider prioritizing (for example, Temporal)
