### ISSUE TITLE
2024 Meeting / Schedule Conflicts

### ISSUE THREAD

**Issue by ctcpip** [openjs-foundation/standards#259]
issue: https://github.com/tc39/Reflector/issues/505

> As we get ready to plan the 2024 schedule of plenary meetings, we'd like to collect a list of any events that should be avoided when selecting dates in order to maximize attendance. For example, conferences where there might be a large number of TC39 delegates.

Please help us identify any major meetings and conferences in 2024 to avoid conflicts. 🙏

**Comment by ljharb** [comment]
- W3C TPAC
 - Github Universe (early November)
 - Open Source Summit
 - various Open JS Worlds
 - various node collaborator summits
 - various OpenSSF Days
 - RenderATL
 - Clarity Conf

**Comment by ctcpip** [comment]
TPAC on our radar, will be in Sept, but still waiting on dates; we are in touch with w3c rep on that one

**Comment by jorydotcom** [comment]
@LeaVerou do you know if the TAG has any of their dates for next year?

**Comment by LeaVerou** [comment]
> @LeaVerou do you know if the TAG has any of their dates for next year?

Noooo, meetings are decided with *way* less lead time than that, usually less than 2 months before.

**Comment by jorydotcom** [comment]
TC39 2024 Plenary Dates have been added to the Open Web Standards Calendar.

**Comment by jorydotcom** [comment]
This is fine to close.
