### ISSUE TITLE
W3C TAG - Call for Nominations Open - Oct. 10-Nov. 7

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/standards#260]
W3C wants to increase the size of the TAG from 6 elected and 3 appointed to 8 and 3. See [the 2023-05-24 Disposition of Comments](https://www.w3.org/Consortium/Process/Drafts/snapshots/2023-05-24-doc#tag-size) for rationale.

We're called on to support this change and I think we should, but I'd like @LeaVerou to weight in before I hit +1.

**Comment by LeaVerou** [comment]
I was one of the people driving that change. 😄 We are way understaffed and absolutely need more people.

**Comment by tobie** [comment]
Done: https://lists.w3.org/Archives/Public/public-new-work/2023Aug/0018.html.

Keeping open for a quick mention during out next call before closing.

**Comment by jorydotcom** [comment]
From email to AC on 9/26: 

     * 10 October - 7 November: Nominations
     * 14 November - 12 December: Election
     * 14 December: Announce election results
     * 1 February 2024: Terms start

The following 3 seats will be up for election:

     * Rossen Atanassov (Microsoft)
     * Dapeng (Max) Liu (Alibaba)
     * Sangwhan Moon (Google)

Note: As announced in August [1], the AB proposed to expand the TAG by
adding 2 more elected seats. If Process 2023.1 gets adopted by 10
October, there will be 5 open seats for this election.

**Comment by jorydotcom** [comment]
Per AC Forum email reflector, there hasn't been an update on the results of the decision to expand the TAG. However the call for nominations has been opened from now until Nov. 7. Updating this issue to be a call for nominations.

**Comment by michaelchampion** [comment]
The TAG has been officially expanded, and there are now 5 open seats up for election.  In https://github.com/openjs-foundation/standards/issues/270 I propose that OpenJS nominate Peter Linss, who has been appointed by the Director/Team for quite some time but now needs to run for election.

**Comment by michaelchampion** [comment]
Nominations are done https://www.w3.org/2023/10/tag-nominations and the election is open until December 12.
