### ISSUE TITLE
OSI affiliate board director elections

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/standards#280]
OSI is running elections for both individual and [affiliate board seats](https://opensource.org/about/board-of-directors/elections/affiliate).

As an affiliate member, we get to cast our vote before Monday, March 18 (i.e. before our next call).

Should we discuss asynchronously in Slack DMs (as we're discussing individual candidates)?

---

_As a side note, [I'm running for an individual member seat](https://opensource.org/board-member/tobie-langel), so if you're an individual OSI member, please consider voting for me._

**Comment by tobie** [comment]
Not having heard from anyone on this topic, and the deadline for voting approaching, I have voted on behalf of the OpenJSF. Happy to discuss during our next call.

**Comment by ljharb** [comment]
I voted individually already, and am fine to go with Tobie’s selection if there’s no time to review beforehand.
