### ISSUE TITLE
Becoming a TC39 delegate

### ISSUE THREAD

**Issue by JakobJingleheimer** [openjs-foundation/standards#283]
Hello!

At the Node.js London collab summit this week, @littledan asked me to champion 2 specifications (mocks and assertions). In order to do that, I would need to join TC39 as a delegate, so he suggested doing that via OpenJS since I'm already a Core Collaborator of Node.js.

Robin suggested I attend the next standards meeting; I don't see it on the calendar, but she said it follows the CPC meeting every other Tuesday (so I think the next one will be noon on 23 April?).

**Comment by UlisesGascon** [comment]
>  I don't see it on the calendar, but she said it follows the CPC meeting every other Tuesday (so I think the next one will be noon on 23 April?).


Not sure why.. but the next meeting scheduled is on the 30th, maybe is expected one in the 16th?

![Screenshot from 2024-04-05 22-25-18](https://github.com/openjs-foundation/standards/assets/5110813/aa996781-a0f3-4eca-a809-6eb8173c7340)

Note: in my image the timezone might be different than yours :)

**Comment by ctcpip** [comment]
We decided to cancel the meeting that would have occurred on the 16th, so as Ulises pointed out, the next one is on the 30th at 17 UTC / 19 CEST

**Comment by JakobJingleheimer** [comment]
Cool, thanks! I'll be there 🙂

**Comment by ctcpip** [comment]
@JakobJingleheimer the next TC39 meeting starts in a couole days and takes place Monday through Friday. perhaps you would be interested in attending as an observer. let me know if that's something you'd like to do. note, you don't have to attend the entire meeting. love your userbame btw lol

**Comment by JakobJingleheimer** [comment]
Sure! Just let me know when!

Thanks 😊

**Comment by ljharb** [comment]
Separately, it’d be great to review the problem statement for those two proposals - “mocks” and “assertions” sound like solutions.

**Comment by JakobJingleheimer** [comment]
> Separately, it’d be great to review the problem statement for those two proposals - “mocks” and “assertions” sound like solutions.

Sure! These a very well-established needs, so should be pretty easy to cover the problem statements 🙂

**Comment by ctcpip** [comment]
https://github.com/tc39/agendas/blob/main/2024%2F04.md

**Comment by JakobJingleheimer** [comment]
> https://github.com/tc39/agendas/blob/main/2024%2F04.md
> 

@ctcpip sorry, I don't understand the agenda—it spans several hours for multiple days, but what is when?

**Comment by ctcpip** [comment]
@JakobJingleheimer please reach out to me on [Matrix](https://github.com/tc39/how-we-work/blob/main/matrix-guide.md):  `@softwarechris:matrix.org`

**Comment by JakobJingleheimer** [comment]
I think this can be closed? Spoilers: I was 🙂

**Comment by ljharb** [comment]
I think this should stay open until @jorydotcom files the TC39 admin issue to get you onboarded.

**Comment by ctcpip** [comment]
> I think this should stay open until @jorydotcom files the TC39 admin issue to get you onboarded.

Jory did that in realtime during the meeting 😃

**Comment by ljharb** [comment]
oh duh, yes, i found it now. closing indeed :-)
