### ISSUE TITLE
Move WG calls to LFX infra

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/standards#292]
We couldn't run this week's call on zoom because no one present was a host. My understanding is moving to LFX infra would fix this.

/cc @bensternthal @jorydotcom

**Comment by bensternthal** [comment]
@jorydotcom, it's time to move this one into LFX. I am happy to do this for you if you can send over (via email) a list of people who should be invited. I do not see attendees in the Google calendar invite.

**Comment by bensternthal** [comment]
Old meeting has been deleted. I'm double checking it's removed everywhere.

**Comment by jorydotcom** [comment]
Closed, as we have done a couple of meetings now on LFX and there have been no outstanding questions.
