### ISSUE TITLE
We should respond to W3C's call to endorse the Ethical Web Principles as a "W3C Statement"

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/standards#299]
Form is here: https://www.w3.org/2002/09/wbs/33280/EthicalWebPrinciples/ (I suspect only visible to @jorydotcom and I).

Document: https://www.w3.org/TR/ethical-web-principles/

As usual, I suggest making the endorsement public and adding a comment for example: "The OpenJS Foundation welcomes the publication of the Ethical Web Principals as a W3C Statement, thereby formalizing the W3C's long held practice of anchoring technical decisions in ethical considerations."

This meeds to be shipped before the Sept. 10, so I'll go ahead and do it over the weekend unless there are objections.

/cc @jorydotcom @LeaVerou

**Comment by ljharb** [comment]
The 10th is Tuesday; please don’t rush unilaterally when there’s no need. Let’s take the time to review it.

**Comment by michaelchampion** [comment]
Agree there is no rush, but there is no real dissent. The only pushback hasn't (yet) appeared in the ballot replies but in a reply to a different message on AC-Forum https://lists.w3.org/Archives/Member/w3c-ac-forum/2024JulSep/0178.html .  So I'm OK with Tobie or Jory responding in the way Tobie suggested.

**Comment by tobie** [comment]
> The 10th is Tuesday; please don’t rush unilaterally when there’s no need. Let’s take the time to review it.

As a matter of etiquette, shooting down such a proposal at such a late stage through a formal objection would be incredibly bad form (unless it is obviously a terrible idea). So the only options here really are: (1) do nothing, (2) vote in favor privately, or (3) vote in favor _and_ make a public statement.

Given the dissenting voices are essentially suggesting that ethical considerations prevent advertisers from tracking people, I think our position should be pretty straightforward. Additionally, these principles come from the TAG and build upon one of the documents @LeaVerou is editing, so we're to some degree already supportive of this work through our support of @LeaVerou TAG role.

**Comment by ljharb** [comment]
I don't expect dissent; I'm just saying that it'd be better to miss the opportunity to support it than to have individuals act unilaterally on behalf of the foundation.

**Comment by tobie** [comment]
> I don't expect dissent; I'm just saying that it'd be better to miss the opportunity to support it than to have individuals act unilaterally on behalf of the foundation.

I'm going to push back on the characterization that this would be "individuals act unilaterally on behalf of the foundation", here. (1) there's an issue filed on the topic, (2) inaction can sometimes be more harmful and drive bad outcomes (arguably the case here), (3) this collab space is specifically empowered to represent the foundation's perspective, (4) the AC Rep and alternate roles Jory and I hold are specifically responsible with responding to such calls, (5) supporting this specific topic is fairly non-contentious, I'd hold a different position if it was, (6) a public statement on the list in support of making this a statement can drive other organisations to support the call too, thus increasing the odds of a ruling in favor in case of a formal objection, so a timely vote is more impactful than a last minute one.

This is not the first time that I'm hearing pushback on having to move fast and last minute on topics like these. I understand the perspective and where this comes from, but there are fairly pragmatic considerations to keep in mind in terms of how much time people can spend on these topics and how little lead time there often is.

Overall, I think that if we want to be able to do anything in this space, we'll have to trust that people are acting with the interest of the foundation in mind when they speak on its behalf and verify that this is case, rather than want to vet everything at the collab space's layer. I don want to point out that the Board is already entrusting the CPC with this role, and the CPC is entrusting this collab space, so it doesn't seem unreasonable to have this collab space entrust individuals in case where decisions are clear cut. Happy to copy/paste this comment in a new issue and have a conversation on the topic in our call if folks find that valuable.

**Comment by ljharb** [comment]
While I generally agree with that, did the W3C really only give 4 days to respond? If they gave more time, why is a Friday the first time we're hearing about it?

I'm not sure why inaction would be harmful here; would it fail if we don't actively endorse it?

I've just read the linked document, and I fully support it (altho 2.11's title needs an Oxford comma :-p ) and think that the foundation should as well - but I think it's reasonable to give more folks a chance to review it themselves, and I don't think a Friday drop with action being taken before the next business day is almost ever reasonable.

**Comment by michaelchampion** [comment]
Hmm, I'm sympathetic with both Jordan and Tobie's points of view on this.  Someone (probably Jory, Tobie, or me) should raise issues EARLY in this collaboration space about upcoming W3C AC votes that might be of interest to the OpenJS community, propose a position or lead a discussion to find one, then nudge one of our AC Reps to vote before the deadline,  (Or well before the deadline if there is a controversy we want to take a stand on).

On the Ethical Web Principles, I think it's reasonable to wait until maybe 24 hours before the deadline just to see if anyone in the OpenJS community has a concern before casting our vote.

**Comment by tobie** [comment]
> Someone (probably Jory, Tobie, or me) should raise issues EARLY in this collaboration space about upcoming W3C AC votes that might be of interest to the OpenJS community, propose a position or lead a discussion to find one, then nudge one of our AC Reps to vote before the deadline, (Or well before the deadline if there is a controversy we want to take a stand on).

This seems sound in theory. In practice, that requires time and organization that I personally don’t have available (and given I was the one raise this, it doesn’t seem that others have it either). It also doesn’t work for most policy issues which we tend to hear about in very ad hoc ways and often at the very last minute. So I don’t think that’s the right model to pursue. At least not at this stage.

**Comment by ljharb** [comment]
I'm always fine with trusted folks (which includes all of you) making unilateral judgement calls to hit a deadline. However, those should be left until the last possible minute, or until there's been sufficient opportunity for the appropriate group to review it, whichever comes first.

**Comment by tobie** [comment]
To be clear, that’s the last minute for me. I have a tight agenda next week, and there’s a high chance this gets entirely dropped if I don’t get it done over the weekend. Also, as mentioned previously, the earlier this gets posted, the bigger its impact on getting others to pay attention (for the record, I brought this to the attention of this collab space because I found out about it through a public comment someone made on the AC-forum list as part of their vote).

**Comment by ljharb** [comment]
That makes sense, thanks for the extra context.

**Comment by michaelchampion** [comment]
> that requires time and organization that I personally don’t have available (and given I was the one raise this, it doesn’t seem that others have it either).

I'll volunteer to raise issues in this repo on any W3C AC votes that seem relevant to OpenJS Foundation, at least 2 weeks before the deadline. Obviously others are free to do so to on things they care about, I have no special status (except as being retired and having time to waste following W3C 😉 ). I had discussed my somewhat nuanced position on the Privacy Principles privately, in hindsight have at least made the Collab Space aware of the document and the open ballot  at the same time

**Comment by tobie** [comment]
@michaelchampion that would be amazing. I believe it would be useful to make you alternate in that case (either in addition to me or instead of me depending on what's possible). /cc @jorydotcom

**Comment by tobie** [comment]
Sent. Including typos in statement. 🤦
