### ISSUE TITLE
Should OpenJS take a position on the W3C Privacy Principles?

### ISSUE THREAD

**Issue by michaelchampion** [openjs-foundation/standards#300]
I should have opened this weeks ago, sorry,  

There is a W3C Advisory Committee ballot open until September 10 to endorse https://www.w3.org/TR/2024/NOTE-privacy-principles-20240813/ as an official "W3C Statement".  There are currently 24 members supporting, one member expressing dissatisfaction with the DOCUMENT but not objecting to publishing it, and one member "formally objecting".  (Details are W3C member-confidential so I can't share them in this public space).

I personally have no strong recommendation.  I strongly support the PRINCIPLE of W3C making a clear statement on web privacy, but this particular document is too long, quasi-academic, and insufficiently practical for my taste.  

If it were up to me, I'd probably vote "Approve As Is" with a comment saying that [the member expressing dissatisfaction with the document] makes some good points that should be considered in a future revision.   But I wouldn't object if others prefer to just quietly vote to support the principle of having Principles ;-) Or or just not vote since nobody raised this issue in a timely manner 🤷

**Comment by ljharb** [comment]
Can you share the basis of the formal objection, even in broad strokes?

**Comment by michaelchampion** [comment]
It is currently private from even W3C members.  Its content will eventually be published, but the not identity of the objecting member .  

In broad strokes it is PROBABLY from a member in the ad-tech industry, at least one of whom has argued for years that W3C should be a “technical standards organization” that doesn’t concern itself with subjective issues such as ethical principles (of which this document is an elaboration of one in the Ethical Web Principles we’re discussing in another thread)

**Comment by ljharb** [comment]
If that's the case, then we should definitely approve as-is, because technical standards simply aren't separable from ethical principles :-)

**Comment by tobie** [comment]
Done.
