### ISSUE TITLE
Should OpenJS Foundation vote on making the W3C Vibration API obsolete?

### ISSUE THREAD

**Issue by michaelchampion** [openjs-foundation/standards#303]
There is a proposal to the W3C Advisory Committee asking approval to mark https://www.w3.org/TR/2016/REC-vibration-20161018/ as an Obsolete Recommendation.

The rationale is:
- There are privacy concerns 
- Firefox and Webkit have removed their implementations, so Chrome/Android is apparently the only implementation  that currently supports it.

More information on the proposal and the responses at https://www.w3.org/2002/09/wbs/33280/obsolete-vibration-api/ (W3C member access required).  One member has objected, preferring to address the privacy concerns via the Permissions API.

Does anyone believe OpenJS should take a position in this ballot?

**Comment by ljharb** [comment]
If only 1 out of 3 browsers supports it, it seems like it should be marked as obsolete, and OpenJS should support that.

**Comment by UlisesGascon** [comment]
+1 I think that make sense to vote in favor of making the API obsolete.

**Comment by michaelchampion** [comment]
I did vote in favor of making the API obsolete.  There are a couple of formal objection that to be honest I don't understand ... they (and all commenters so far) seem to agree with the Devices and Sensors Workin Group's plan to develop a new version, using the emerging Permissions API to address the privacy concerns. The vote has been extended until November 5 so if anyone feels we should change our vote, let me know.

**Comment by michaelchampion** [comment]
Completed
