### ISSUE TITLE
October 2024 W3C Ballot questions OpenJS might take a stand on

### ISSUE THREAD

**Issue by michaelchampion** [openjs-foundation/standards#306]
Stealing shamelessly from AB Chair Wendy Reid's message to the Advisory Committee, here's what we could express an opinion on if we wish:

_Sustainable Web Interest Group Charter
Reply by: October 16, 2024 (23:59 Boston Time)
Summary: In response to suggestions made during the AC review of a proposed Sustainable Web Working Group Charter, the staff is re-proposing an Interest Group. This is a call for review of a proposed Sustainable Web Interest Group Charter.
Link to Charter: https://www.w3.org/2024/09/sustyweb-charter-202409.html
Link to Questionnaire: https://www.w3.org/2002/09/wbs/33280/SustyWeb/_

**Based on guidance at the last Collab Space call, I have voted Supports this charter as-is**. I can change it if anyone strongly disagrees.  (But there is no disagreement I'm aware of among W3C members).
 
_Security Interest Group Charter Proposed Changes
Reply by: October 19, 2024 (23:59 Boston Time)
Summary: Following the AC Review, we are proposing the following substantial change: Adding the “Threat Model for the Web” deliverable.
Link to Charter: https://www.w3.org/2024/04/proposed-wg-webappsec.html
Link to Questionnaire: https://www.w3.org/2002/09/wbs/33280/sing-tmw/_
**There's some disagreement I don't understand, on procedural grounds.  I'll vote if anyone thinks it's important for our community**

_Vibration API (Second Edition) as Obsolete Recommendation
Reply by: November 5, 2024 (23:59 Boston Time)
Summary: The reason for this proposal is that this specification no longer has multiple implementations on the Web platform. The W3C needs to communicate this as clearly as possible to the Web community.
Link to Questionnaire: https://www.w3.org/2002/09/wbs/33280/obsolete-vibration-api/_
 **See https://github.com/openjs-foundation/standards/issues/303**

_WebRTC: Real-time Communication in Browsers Proposed Amendments
Reply by: December 8, 2024 (23:59 Boston Time)
Summary: A list of proposed amendments can be found here: https://www.w3.org/TR/2024/REC-webrtc-20241008/Overview.html#proposed-amendments
Link to document: https://www.w3.org/TR/2024/REC-webrtc-20241008/
Link to Questionnaire: https://www.w3.org/2002/09/wbs/33280/webrtc-2024-amendments/_
 
**WebRTC makes my head hurt ;-) .. seeking opinions on this and whether we should take a stand on them in the ballot** 

_Call for Nominations: Technical Architecture Group (TAG)
Reply by: November 5, 2024 (23:59 Boston Time)
AC representatives are invited to nominate candidates for the upcoming TAG election. There are 4 seats up for election. The terms will run from February 1, 2025 to January 31, 2027.
Link to nomination form: https://www.w3.org/2002/09/wbs/33280/tag-202410/_

**We have supported @LeaVerou for two terms now, I don't know if she is interested in being nominated again.  Let's discuss what she wants and whether we have another candidate if she plans to get on with life after the TAG**

**Comment by ljharb** [comment]
nvm's threat model, per request: https://github.com/nvm-sh/nvm/blob/master/.github/THREAT_MODEL.md
