### ISSUE TITLE
TPAC ReCap 

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#31]
On our way back from TPAC & wanted to document some items for triage/discussion:

First, we had a breakout session wherein we chatted with folks from the foundation and W3C communities about ways we could collaborate with each other. You can checkout the scribed minutes here: https://www.w3.org/2019/09/18-openjs-minutes.html (thank you @bkardell for the minutes!). I think there were several good ideas in there that should be popped out into the issues here.

There was also a session on JS Built-in Modules (see https://www.w3.org/2019/09/18-jsbuiltin-minutes.html), and "web capabilities" (aka project fugu, see https://w3c.github.io/tpac-breakouts/sessions.html#capable-web) which folks may be interested in hearing recaps of.  

Ada Rose Cannon shared some bots/scripts she’s been using to run immersive web WG meetings and I think there are some advantages to what she’s doing over our current ‘make meeting’ tool, namely that this is a simple bot interface that anyone chairing the meeting can use. I’d like to propose we try it out for our standards meetings. WDYT? (cc @mhdawson) See: https://glitch.com/~probot-label 

Finally, I think those who attended would be happy to make a more comprehensive report back to the group - what format would folks like to see that in? cc @christian-bromann @bkardell

**Comment by MylesBorins** [comment]
Closing as this has been open for a minute
