### ISSUE TITLE
OSI Affiliate Membership

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/standards#32]
https://opensource.org/affiliates

It seems like with fit the criteria listed in https://opensource.org/AffiliateRequirements

Perhaps could be a good place to collaborate considering our projects all us OSI licenses. LMK if you think this should be on CPC repo instead

**Comment by ehashman** [comment]
I would be super thrilled if OpenJS Foundation joined @OpenSourceOrg as an affiliate :tada: I'm on the Board and I'm also the chair of our Membership Committee.

Here are the steps in this process as an FYI:

1. Reach out via the [OSI Contact Form](https://opensource.org/contact), category "Affiliate Program" (that makes sure it goes to Patrick Masson, our general manager).
2. Prepare a doc as per requirements under [Non-Profit Organizations on this page](https://opensource.org/AffiliateRequirements). Mostly it's a matter of collecting links, not a lot of original content required.
3. Print, sign, and scan the [Affiliate Agreement](https://opensource.org/affiliateAgreement).
4. Send all of the above to Patrick once he's responded to your inquiry.

Please reach out to me if you have any questions.

**Comment by sendilkumarn** [comment]
@MylesBorins Thanks for bringing this up. I am all for it 👍 

@ehashman 👋

**Comment by MylesBorins** [comment]
Board elections are spinning up in a month which includes 1 seat for affiliate members

https://opensource.org/elections

Adding to CPC agenda so we can get the ball rolling if we want to join

**Comment by MylesBorins** [comment]
Both CPC and Standards group had no concerns with moving forward with this

@brianwarner @rginn @jorydotcom would you be able to kick this off? It is slightly time sensitive if we want to run in the affiliate election for the OSI board.

**Comment by ehashman** [comment]
Each affiliate is able to nominate one individual to run for an OSI board seat and may vote in the affiliate election. They must be affiliate members before the election begins to participate. I think we might have one more board meeting before that date, but it's not a regular meeting, so it's unclear to me if OpenJS would be able to become an affiliate in time for the cutoff this year.

As an alternative, I thought I might mention: if folks associated with OpenJS are interested in running for the board of the OSI, I would recommend signing up as an individual member (by Jan. 27th) and self-nominating, or seeking out another affiliate for a nomination.

**Comment by jorydotcom** [comment]
I believe this can be closed, since the board approved our affiliate membership and we are now at the stage of electing our representative.
