### ISSUE TITLE
Interest in a follow-on TC39 proposals review call?

### ISSUE THREAD

**Issue by littledan** [openjs-foundation/standards#4]
At the OpenJSF Collaborator Summit, I led a session presenting a few proposals at TC39, and talking them over with people present. It was really helpful for me, as a TC39 delegate, to hear your thoughts, and maybe it was interesting to some of you to hear about these proposals as well. If folks would be interested in having a similar conversation in September or October 2019 (but this time, in a call), I'd be happy to have another one.

**Comment by MylesBorins** [comment]
I definitely would be interested in helping with and participating in such a call

**Comment by ljharb** [comment]
same

**Comment by sendilkumarn** [comment]
@littledan I am interested too, to participate in the call

**Comment by joesepi** [comment]
Count me in, please

**Comment by littledan** [comment]
I plan to follow up with a Doodle here in September.

**Comment by littledan** [comment]
I think this will be subsumed by the meetings @jorydotcom and @sendilkumarn have been talking about, to precede TC39 and get feedback for the OpenJSF delegate(s). So, I'm not creating this Doodle right now.

**Comment by mikesamuel** [comment]
Closing since it seems like the collab summit is sorted.  @littledan, please reopen if this was a mistake.
