### ISSUE TITLE
Audit membership list

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/standards#53]
As mentioned in https://github.com/openjs-foundation/standards/pull/52 there was an existing `standards` group in the `openjs-foundation` org. The full list has been appended to the README

@openjs-foundation/standards if you are getting a ping right now it is because you are in that list.

How do we want to handle folks that are already on the team but have not been participating.

personally I think it would be fair to leave this issue open for 2 weeks and automatically keep anyone who chimes in and says they want to remain involved. If someone doesn't respond we can remove them.

Thoughts?

**Comment by christian-bromann** [comment]
Sounds reasonable to me 👍

**Comment by mikesamuel** [comment]
Chiming 🎐

**Comment by antsmartian** [comment]
I wanted to be part of it.
