### ISSUE TITLE
Chartering the standards team

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/standards#58]
I think we should ask the CPC to charter this group to oversee / own the OpenJS foundations engagement in standards activities. This would allow us to independently make decisions without a need to proxy them through the CPC. To be clear I 100% trust the CPC to make good decisions, but those who are active in these decisions are participating in this group. It is not efficient for either committee to have to bounce ideas between the two spaces.

Rough idea for steps for us: 

* Write charter
* Apply with CPC for official chareter

Rough idea for steps for CPC:

* Reach consensus that chartered working groups will be a thing
* Document process for chartering

Anything missing?

**Comment by joesepi** [comment]
One thing I have in flight @MylesBorins is moving admin docs from Node.js to OpenJSF. Draf PR: https://github.com/openjs-foundation/cross-project-council/pull/443

**Comment by mikesamuel** [comment]
As discussed in meeting, we can capture ideas in [this shared doc](https://docs.google.com/document/d/1txG3CwoTnnDWS1lJOEEem-Acp8z9klRgabA6m52mV1k/edit).

Link allows edit, but if it's abused, I can tighten down perms.

**Comment by MylesBorins** [comment]
We've agreed on copy for the scope

---

# Scope

The purpose of the Standards Working Group is to act as a facilitator for OpenJS Foundation projects to support their engagement in various Standards Organizations, Working Groups, Technical Committees, and other spaces where internationally recognized standards are collaborated upon.

Responsibilities include:
* approve and support OpenJS Foundation project contributors in attending meetings held by standards organizations
* make OpenJS Foundation project contributors aware of developments in relevant standards
* help OpenJS Foundation projects formulate a standards strategy 
* support new contributors to standards-making activities
* mentor project contributors who are unfamiliar with standards-making processes
* make recommendations to the Cross Project Council regarding standards organization membership
* managing ongoing relationships with standards ogranizations
* ensuring that OpenJS representatives are aware of the responsibility of being a delegate of the foundation as outlined in [the membership expectations](https://github.com/openjs-foundation/standards/blob/master/MEMBER_EXPECTATIONS.md)
* facilitate when different projects' needs conflict

**Comment by joesepi** [comment]
The cpc admin docs have landed: https://github.com/openjs-foundation/cross-project-council/pull/443

**Comment by MylesBorins** [comment]
We are officially chartered!
