### ISSUE TITLE
Standards-related Travel Budget Clarification

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#6]
As the JS Foundation, the Board provided a budget to send reps to TC39 and W3C meetings. We need clarity as to whether this budget continues for H2 2019; or whether it should be part of the overall travel budget for the remainder of the year (which may require agreement from the Node TSC, as they are currently managing). 

We should also think about what makes sense in 2020 and beyond - for simplicity, we may want to just have one overall travel budget instead of two separate (one for standards, one for collab summit & everything else). To be clear this would be a decision that the CPC would make, but we could discuss our preferences / ideal scenarios.

**Comment by dtex** [comment]
The budget was set at $60k (US) for 2020. I suspect not much of that was used. Regardless, it looks like the CPC has handled this already with https://github.com/openjs-foundation/cross-project-council/pull/441

For those interested in the re-imbursement process, it is documented here: 

https://github.com/openjs-foundation/cross-project-council/blob/master/TRAVEL_FUND/reimbursement_process.pdf
