### ISSUE TITLE
Participation in the Unicode MessageFormat WG

### ISSUE THREAD

**Issue by eemeli** [openjs-foundation/standards#64]
This is a request following the "Attending External Standards Meetings" governance guideline.

I wish to continue participating in the meetings of the [Unicode MessageFormat Working Group](https://github.com/unicode-org/message-format-wg/), a subgroup of the Unicode CLDR-TC, as a representative of the OpenJS Foundation.

The foundation is not yet a member of the Unicode Consortium, but this is currently progressing under issue #43, with a likely result of the foundation being invited to and joining as an affiliate member.

The working group meets online monthly, using Google Hangouts. The next meeting is scheduled for 23 March 2020. There is no current plan for an in-person meeting, but such may be organised at some point. Participation in the online meetings is of course free; if an in-person meeting does happen, I may approach the Standards group or the CPC separately about that.

My intent in participating in this working group is to help make sure the best possible MessageFormat standard is developed out of it, in particular for its implementation as a part of the JavaScript `Intl` object. In my participation I am not only representing `messageformat` the OpenJS project, but also JavaScript developers in general.

**Comment by jorydotcom** [comment]
AI: open a PR to document this
