### ISSUE TITLE
Request to attend TC39 as OpenJS delegate

### ISSUE THREAD

**Issue by devsnek** [openjs-foundation/standards#66]
I'd like to attend the March TC39 meeting as a delegate for the OpenJS Foundation. The meeting is from March 31 to April 2, and I would be attending remotely. The goal of this attendance is to advance `import.meta` to stage 4. This will be a joint effort with @MylesBorins.

**Comment by MylesBorins** [comment]
I want to +1 this engagement.

**Comment by MylesBorins** [comment]
Approved!
