### ISSUE TITLE
Documenting approved representatives

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/standards#67]
Dawns on me that we don't currently have a way to document approved OpenJS Reps to standards orgs. This could be both on a per engagement basis or a permanent assignment.

How do folks feel about keeping some markdown in the repo and updating the governance to have folks make a PR to it?

**Comment by ljharb** [comment]
Makes sense to me.

**Comment by christian-bromann** [comment]
Drafted a PR for this: #78
