### ISSUE TITLE
When are the meetings?

### ISSUE THREAD

**Issue by dtex** [openjs-foundation/standards#69]
Is there a schedule somewhere?

I see messages on Slack immediately before meetings start, but I need to plan ahead to be able to attend. 

I'm probably gonna feel dumb when someone points out that they were in plain sight the whole time.

**Comment by MylesBorins** [comment]
Hey Donovan. The meetings are every other tuesday at 2pm ET. There is a
calendar at http://calendar.openjsf.org/ and issues are opened on Monday of
the week of the meeting.

**Comment by dtex** [comment]
Thank you.
