### ISSUE TITLE
Standards Working Group Meeting 2019-07-02

### ISSUE THREAD

**Issue by sendilkumarn** [openjs-foundation/standards#7]
Let us kickstart our first meeting. 

Created a Doodle [here](https://doodle.com/poll/u7m486w3ws9mtxu2).

Agenda Doc [here](https://docs.google.com/document/d/1TLRUbXD73Z8pv8OqA2rTo6RK_fnSq81kkmAQAc2JikU/edit?usp=sharing). 

Purpose: Based on the last meeting notes from [here](https://github.com/openjs-foundation/standards/blob/master/meeting-notes/2019.05.31_collabsummit_session.md). 

cc @jorydotcom

**Comment by littledan** [comment]
Could you say something about what the purpose of this meeting is? Also, would it be possible to create a Doodle with fewer entries in it? (related, but presumably different: [TC39-related meeting](https://github.com/openjs-foundation/standards/issues/4))

**Comment by sendilkumarn** [comment]
> Could you say something about what the purpose of this meeting is?

**Comment by littledan** [comment]
Well, I will be happy to join this group in September.

**Comment by MylesBorins** [comment]
The times on the doodle seem kind of odd for me. There are no during ET business hours for Monday the 24th, no times on wednesday the 26th and no times during business hours on the 27th. Why is that?

**Comment by sendilkumarn** [comment]
@MylesBorins I selected the whole day in CEST (timezone), I guess that is the reason why it is showing like this in the Doodle.

**Comment by sendilkumarn** [comment]
@jorydotcom Thanks. I updated the Doodle likewise.

**Comment by sendilkumarn** [comment]
Based on the Doodle, let us have the meeting on July 2 - 2000h CEST.

Meeting link [here](https://calendar.google.com/event?action=TEMPLATE&tmeid=MWRxMHEzb25wOXFwbGhuYzdybDBjZ2NyZ28gc2VuZGlsa3VtYXJuLm9wZW5zb3VyY2VAbQ&tmsrc=sendilkumarn.opensource%40gmail.com)

Interested ones 

Please use the following emoji reactions in this post to indicate your
availability.

👍 - Attending
👎 - Not attending
😕 - Not sure yet

**Comment by sendilkumarn** [comment]
Closing the issue as the meeting happened 🙂
