### ISSUE TITLE
Ideas for Collab Summit sessions from the Standards WG

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#76]
During our meeting in #73, we brainstormed session ideas including: 

* Standards WG 101 - how projects can take advantage
* Panel or Intro session to how different standards groups work - e.g. W3C, Ecma
* Revised "Patterns for Participation" workshop
* @eemeli could do a session on the Unicode consortium
* Looking forward - what areas do we want to focus on in the next ~2-5 years

We should refine these ideas (and add more) and draft up session proposals for the /summit repo.

**Comment by dtex** [comment]
The Collab Summit sessions I've personally attended have all been hands-on learning experiences. When it comes to standards I'm not sure that we have options for that, so this would either be an expanded, public meeting or simply a speaker addressing attendees. 

If the former, I think it would be interesting to solicit approaches to bigger issues, such as: 
* What is the role of an OpenJS representative?
* How do we collect input from the maintainers of Foundation Projects?
* How do we share information with the maintainers of Foundation Projects?
These are all complicated, and potentially thorny issues, so it might be smart to ask for help.

If the latter, a speaker could cover:
* Which standards bodies the Foundation has members on, and the roles of each of those bodies
* The language and grammar of standards
* How to read and understand 262

**Comment by sendilkumarn** [comment]
This is awesome. 

> Standards WG 101

This was the initial idea that I had. This should include (but not limited to):
* Why we exist? What problems are we solving? (It is also important to clarify what we are not)
* How does the Project / JavaScript ecosystem / Individuals use Standards organisation
* Some historical examples that could have been solved with the Standards group.
* How some standards group work and how to on-board and contribute help to them.
* The common language and standards.
* What we will focus in the future?

On the other hand, It will be awesome to have a panel / discussion (with other standards organization delegates) to discuss about the issues that they are facing currently and understand what they expect from "Standards" Working Group.

**Comment by dtex** [comment]
The 2020 Collab Summit has come and gone (It was great BTW). I'm closing this issue but we should remember it's here if we need ideas next year.
