### ISSUE TITLE
Craft the Standards Working Group Mission statement

### ISSUE THREAD

**Issue by dtex** [openjs-foundation/standards#80]
... and put it at the top of the readme. Thinking about the announcement blog post, and realizing that this isn't clearly defined.

**Comment by dtex** [comment]
Short Strawman (the shorter the better IMHO): 

The Standards Working Group was established so that the OpenJS Foundation could actively monitor and contribute to the evolution of technologies upon which the foundation's projects depend.

**Comment by MylesBorins** [comment]
added to agenda so we can discuss next meeting

**Comment by mikesamuel** [comment]
I like it but I'm concerned that someone reading this may come away with the impression that standards team members are supposed to be the ones participating in the standards bodies and not that we can help them help themselves.

How about something like:

The Standards Working Group actively monitors evolving standards to educate projects about developments that might affect them, and helps projects formulate standards strategies and advance them before standards bodies.

**Comment by dtex** [comment]
This makes sense and I think it is a good clarification. Any changes I would offer would be in favor of concision. If anyone is inclined to play word golf they should go for it, otherwise, I vote "ship it".

**Comment by dtex** [comment]
Closed by #88
