### ISSUE TITLE
Request to participate in TC39 as OpenJS delegate

### ISSUE THREAD

**Issue by ljharb** [openjs-foundation/standards#83]
Although it's likely fine to (again) participate as an invited expert, I'd like to continue editorship, code of conduct committee membership, and committee participation as a delegate of the OpenJS Foundation.

**Comment by dtex** [comment]
I think this fell off the radar during tangential discussions. It's similar to my request #24

What are the next steps?

We should probably update the Member Expectations doc to document the process for confirmation.

**Comment by ljharb** [comment]
Since my employer plans to join Ecma, and being an invited expert has not impeded my participation, I'll close this for now.
