### ISSUE TITLE
Team meeting agenda didn't get created (and link for today)

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/standards#85]
@mhdawson any idea why?

Joining the meeting
link for participants: Zoom link: https://zoom.us/j/599005386

For those who just want to watch: https://livestream.openjsf.org

**Comment by joesepi** [comment]
I wonder if my recent update broke something.
https://github.com/nodejs/create-node-meeting-artifacts/blame/master/templates/meeting_base_standards

**Comment by ljharb** [comment]
Possibly the calendar event just needs to be renamed?

**Comment by joesepi** [comment]
Looks like that is the case @ljharb -- I'm working on getting the calendar event updated.

**Comment by mhdawson** [comment]
They do have to match up :)

**Comment by mhdawson** [comment]
If you notice in advance I can re-run the job to create after the Calendar entry is updated.

**Comment by brianwarner** [comment]
Hi all, the calendar invite has been updated to `Standards Working Group Meeting`.

**Comment by mhdawson** [comment]
If it was something other than what @brianwarner indicated in the previous post before that would explain it. I has to match what is configured in the automation: https://github.com/nodejs/create-node-meeting-artifacts/blob/master/templates/meeting_base_standards

**Comment by sendilkumarn** [comment]
Did we create a meeting note for this meeting?

**Comment by MylesBorins** [comment]
I'm guessing there is no meeting today due to openjs World

**Comment by sendilkumarn** [comment]
I was asking about the meeting that happened on 21-Apr-2020.
