### ISSUE TITLE
Nominate OpenJS Foundation representative for OSI

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/standards#89]
The OpenJS Foundation was recently accepted as an affiliate member of OSI.  I've opened an issue in the CPC repo to collect nominations: https://github.com/openjs-foundation/cross-project-council/issues/540

I'm asking for self-nominations by Tuesday, May 12th at EoD.  I'll close this issue at that point.

**Comment by MylesBorins** [comment]
Consider this a self nomination

**Comment by brianwarner** [comment]
I'm sorry, I wasn't clear on the original post, I'm attempting to collect nominations in one thread, would you mind moving your comment over to the other? :-)

**Comment by MylesBorins** [comment]
Not to be too pedantic, but I think this is the proper thread to get
nominations as the will be managed by the standards wg

**Comment by brianwarner** [comment]
Just confirming per discussions yesterday, this is the place for nominations.  I'll update the issue in the CPC repo.

**Comment by brianwarner** [comment]
As there were no further nominations by May 12th EoD, @MylesBorins will be the rep to OSI.  I'll let our contact at OSI know, and close this issue.  Thanks Myles!
